driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
    - recipe[apt::default]

  - name: debian-8.1
    - recipe[apt::default]
  - name: fedora-21
  - name: fedora-22
  - name: freebsd-10.1
  - name: ubuntu-12.04
    - recipe[apt::default]

  - name: ubuntu-14.04
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[squid::default]
    attributes:
      squid:
        cache_size: 10
        cache_mem: 10
